global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'asma-order-producer'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8082']
        # Usa 'host.docker.internal:8082' per raggiungere l'applicazione dall'interno di un container Docker

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
        # Se il Node Exporter è eseguito localmente fuori da Docker, questo è corretto.
        # Se anche Node Exporter è in un container, potresti aver bisogno di usare 'host.docker.internal:9100'
